/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBuktiPotongIndexRouteImport } from './routes/_app/bukti-potong/index'
import { Route as AppElemenIndexRouteImport } from './routes/_app/elemen/index'
import { Route as AppKalkulatorIndexRouteImport } from './routes/_app/kalkulator/index'
import { Route as AppKaryawanIndexRouteImport } from './routes/_app/karyawan/index'
import { Route as AppNonPegawaiIndexRouteImport } from './routes/_app/non-pegawai/index'
import { Route as AppPemotongIndexRouteImport } from './routes/_app/pemotong/index'
import { Route as AppPenghasilanIndexRouteImport } from './routes/_app/penghasilan/index'
import { Route as AppReferensiIndexRouteImport } from './routes/_app/referensi/index'
import { Route as AppSpreadsheetIndexRouteImport } from './routes/_app/spreadsheet/index'
import { Route as AppSummaryIndexRouteImport } from './routes/_app/summary/index'
import { Route as AppTahunanIndexRouteImport } from './routes/_app/tahunan/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBuktiPotongIndexRoute = AppBuktiPotongIndexRouteImport.update({
  id: '/bukti-potong/',
  path: '/bukti-potong/',
  getParentRoute: () => AppRoute,
} as any)
const AppElemenIndexRoute = AppElemenIndexRouteImport.update({
  id: '/elemen/',
  path: '/elemen/',
  getParentRoute: () => AppRoute,
} as any)
const AppKalkulatorIndexRoute = AppKalkulatorIndexRouteImport.update({
  id: '/kalkulator/',
  path: '/kalkulator/',
  getParentRoute: () => AppRoute,
} as any)
const AppKaryawanIndexRoute = AppKaryawanIndexRouteImport.update({
  id: '/karyawan/',
  path: '/karyawan/',
  getParentRoute: () => AppRoute,
} as any)
const AppNonPegawaiIndexRoute = AppNonPegawaiIndexRouteImport.update({
  id: '/non-pegawai/',
  path: '/non-pegawai/',
  getParentRoute: () => AppRoute,
} as any)
const AppPemotongIndexRoute = AppPemotongIndexRouteImport.update({
  id: '/pemotong/',
  path: '/pemotong/',
  getParentRoute: () => AppRoute,
} as any)
const AppPenghasilanIndexRoute = AppPenghasilanIndexRouteImport.update({
  id: '/penghasilan/',
  path: '/penghasilan/',
  getParentRoute: () => AppRoute,
} as any)
const AppReferensiIndexRoute = AppReferensiIndexRouteImport.update({
  id: '/referensi/',
  path: '/referensi/',
  getParentRoute: () => AppRoute,
} as any)
const AppSpreadsheetIndexRoute = AppSpreadsheetIndexRouteImport.update({
  id: '/spreadsheet/',
  path: '/spreadsheet/',
  getParentRoute: () => AppRoute,
} as any)
const AppSummaryIndexRoute = AppSummaryIndexRouteImport.update({
  id: '/summary/',
  path: '/summary/',
  getParentRoute: () => AppRoute,
} as any)
const AppTahunanIndexRoute = AppTahunanIndexRouteImport.update({
  id: '/tahunan/',
  path: '/tahunan/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/bukti-potong/': typeof AppBuktiPotongIndexRoute
  '/elemen/': typeof AppElemenIndexRoute
  '/kalkulator/': typeof AppKalkulatorIndexRoute
  '/karyawan/': typeof AppKaryawanIndexRoute
  '/non-pegawai/': typeof AppNonPegawaiIndexRoute
  '/pemotong/': typeof AppPemotongIndexRoute
  '/penghasilan/': typeof AppPenghasilanIndexRoute
  '/referensi/': typeof AppReferensiIndexRoute
  '/spreadsheet/': typeof AppSpreadsheetIndexRoute
  '/summary/': typeof AppSummaryIndexRoute
  '/tahunan/': typeof AppTahunanIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/bukti-potong': typeof AppBuktiPotongIndexRoute
  '/elemen': typeof AppElemenIndexRoute
  '/kalkulator': typeof AppKalkulatorIndexRoute
  '/karyawan': typeof AppKaryawanIndexRoute
  '/non-pegawai': typeof AppNonPegawaiIndexRoute
  '/pemotong': typeof AppPemotongIndexRoute
  '/penghasilan': typeof AppPenghasilanIndexRoute
  '/referensi': typeof AppReferensiIndexRoute
  '/spreadsheet': typeof AppSpreadsheetIndexRoute
  '/summary': typeof AppSummaryIndexRoute
  '/tahunan': typeof AppTahunanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/bukti-potong/': typeof AppBuktiPotongIndexRoute
  '/_app/elemen/': typeof AppElemenIndexRoute
  '/_app/kalkulator/': typeof AppKalkulatorIndexRoute
  '/_app/karyawan/': typeof AppKaryawanIndexRoute
  '/_app/non-pegawai/': typeof AppNonPegawaiIndexRoute
  '/_app/pemotong/': typeof AppPemotongIndexRoute
  '/_app/penghasilan/': typeof AppPenghasilanIndexRoute
  '/_app/referensi/': typeof AppReferensiIndexRoute
  '/_app/spreadsheet/': typeof AppSpreadsheetIndexRoute
  '/_app/summary/': typeof AppSummaryIndexRoute
  '/_app/tahunan/': typeof AppTahunanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/bukti-potong/'
    | '/elemen/'
    | '/kalkulator/'
    | '/karyawan/'
    | '/non-pegawai/'
    | '/pemotong/'
    | '/penghasilan/'
    | '/referensi/'
    | '/spreadsheet/'
    | '/summary/'
    | '/tahunan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/api/auth/$'
    | '/bukti-potong'
    | '/elemen'
    | '/kalkulator'
    | '/karyawan'
    | '/non-pegawai'
    | '/pemotong'
    | '/penghasilan'
    | '/referensi'
    | '/spreadsheet'
    | '/summary'
    | '/tahunan'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/api/auth/$'
    | '/_app/bukti-potong/'
    | '/_app/elemen/'
    | '/_app/kalkulator/'
    | '/_app/karyawan/'
    | '/_app/non-pegawai/'
    | '/_app/pemotong/'
    | '/_app/penghasilan/'
    | '/_app/referensi/'
    | '/_app/spreadsheet/'
    | '/_app/summary/'
    | '/_app/tahunan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bukti-potong/': {
      id: '/_app/bukti-potong/'
      path: '/bukti-potong'
      fullPath: '/bukti-potong/'
      preLoaderRoute: typeof AppBuktiPotongIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/elemen/': {
      id: '/_app/elemen/'
      path: '/elemen'
      fullPath: '/elemen/'
      preLoaderRoute: typeof AppElemenIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kalkulator/': {
      id: '/_app/kalkulator/'
      path: '/kalkulator'
      fullPath: '/kalkulator/'
      preLoaderRoute: typeof AppKalkulatorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/karyawan/': {
      id: '/_app/karyawan/'
      path: '/karyawan'
      fullPath: '/karyawan/'
      preLoaderRoute: typeof AppKaryawanIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/non-pegawai/': {
      id: '/_app/non-pegawai/'
      path: '/non-pegawai'
      fullPath: '/non-pegawai/'
      preLoaderRoute: typeof AppNonPegawaiIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pemotong/': {
      id: '/_app/pemotong/'
      path: '/pemotong'
      fullPath: '/pemotong/'
      preLoaderRoute: typeof AppPemotongIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/penghasilan/': {
      id: '/_app/penghasilan/'
      path: '/penghasilan'
      fullPath: '/penghasilan/'
      preLoaderRoute: typeof AppPenghasilanIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/referensi/': {
      id: '/_app/referensi/'
      path: '/referensi'
      fullPath: '/referensi/'
      preLoaderRoute: typeof AppReferensiIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spreadsheet/': {
      id: '/_app/spreadsheet/'
      path: '/spreadsheet'
      fullPath: '/spreadsheet/'
      preLoaderRoute: typeof AppSpreadsheetIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/summary/': {
      id: '/_app/summary/'
      path: '/summary'
      fullPath: '/summary/'
      preLoaderRoute: typeof AppSummaryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tahunan/': {
      id: '/_app/tahunan/'
      path: '/tahunan'
      fullPath: '/tahunan/'
      preLoaderRoute: typeof AppTahunanIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppBuktiPotongIndexRoute: typeof AppBuktiPotongIndexRoute
  AppElemenIndexRoute: typeof AppElemenIndexRoute
  AppKalkulatorIndexRoute: typeof AppKalkulatorIndexRoute
  AppKaryawanIndexRoute: typeof AppKaryawanIndexRoute
  AppNonPegawaiIndexRoute: typeof AppNonPegawaiIndexRoute
  AppPemotongIndexRoute: typeof AppPemotongIndexRoute
  AppPenghasilanIndexRoute: typeof AppPenghasilanIndexRoute
  AppReferensiIndexRoute: typeof AppReferensiIndexRoute
  AppSpreadsheetIndexRoute: typeof AppSpreadsheetIndexRoute
  AppSummaryIndexRoute: typeof AppSummaryIndexRoute
  AppTahunanIndexRoute: typeof AppTahunanIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppBuktiPotongIndexRoute: AppBuktiPotongIndexRoute,
  AppElemenIndexRoute: AppElemenIndexRoute,
  AppKalkulatorIndexRoute: AppKalkulatorIndexRoute,
  AppKaryawanIndexRoute: AppKaryawanIndexRoute,
  AppNonPegawaiIndexRoute: AppNonPegawaiIndexRoute,
  AppPemotongIndexRoute: AppPemotongIndexRoute,
  AppPenghasilanIndexRoute: AppPenghasilanIndexRoute,
  AppReferensiIndexRoute: AppReferensiIndexRoute,
  AppSpreadsheetIndexRoute: AppSpreadsheetIndexRoute,
  AppSummaryIndexRoute: AppSummaryIndexRoute,
  AppTahunanIndexRoute: AppTahunanIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
